/*
 *     Generated by class-dump 3.3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <AppKit/NSView.h>

@class NSButton, NSCell, NSMutableArray, NSString;

@interface NSFrameView : NSView
{
    unsigned long long styleMask;
    NSString *_title;
    NSCell *titleCell;
    NSButton *closeButton;
    NSButton *zoomButton;
    NSButton *minimizeButton;
    BOOL resizeByIncrement;
    BOOL unused;
    unsigned char tabViewCount;
    struct CGSize resizeParameter;
    int shadowState;
    NSMutableArray *edgeResizingTrackingAreas;
}

+ (void)initialize;	// IMP=0x002033d7
+ (void)initTitleCell:(id)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x0042cbcd
+ (struct CGRect)frameRectForContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x0042cb02
+ (struct CGRect)contentRectForFrameRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x0042cb32
+ (struct CGSize)minFrameSizeForMinContentSize:(struct CGSize)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x0042cb62
+ (struct CGSize)minContentSizeForMinFrameSize:(struct CGSize)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x0042cb68
+ (double)minFrameWidthWithTitle:(id)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x0042cb6e
+ (unsigned long long)_validateStyleMask:(unsigned long long)arg1;	// IMP=0x0042cb78
- (id)initWithFrame:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 owner:(id)arg3;	// IMP=0x00203e99
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0042d267
- (void)dealloc;	// IMP=0x002434e6
- (void)shapeWindow;	// IMP=0x0042d1da
- (void)tileAndSetWindowShape:(BOOL)arg1;	// IMP=0x00205569
- (void)tile;	// IMP=0x0042d1c4
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x0023a97d
- (void)_drawFrameRects:(struct CGRect)arg1;	// IMP=0x0042ca0c
- (void)drawFrame:(struct CGRect)arg1;	// IMP=0x0042ca12
- (void)drawThemeContentFill:(struct CGRect)arg1 inView:(id)arg2;	// IMP=0x0008376b
- (void)drawWindowBackgroundRect:(struct CGRect)arg1;	// IMP=0x0042d18e
- (void)drawWindowBackgroundRegion:(struct CGSRegionObject *)arg1;	// IMP=0x0027d306
- (double)contentAlpha;	// IMP=0x00084433
- (void)_windowChangedKeyState;	// IMP=0x000761de
- (void)_updateButtonState;	// IMP=0x0042ca18
- (BOOL)_isSheet;	// IMP=0x0042ca1e
- (BOOL)_isUtility;	// IMP=0x0042ca26
- (void)setShadowState:(long long)arg1;	// IMP=0x000cdf02
- (long long)shadowState;	// IMP=0x00061610
- (BOOL)_canHaveToolbar;	// IMP=0x0042ca2e
- (BOOL)_toolbarIsInTransition;	// IMP=0x0042ca36
- (BOOL)_toolbarIsShown;	// IMP=0x0042ca3e
- (BOOL)_toolbarIsHidden;	// IMP=0x0042ca46
- (BOOL)_toolbarIsManagedByExternalWindow;	// IMP=0x0042ca4e
- (void)_showToolbarWithAnimation:(BOOL)arg1;	// IMP=0x0042ca56
- (void)_hideToolbarWithAnimation:(BOOL)arg1;	// IMP=0x0042ca5c
- (double)_distanceFromToolbarBaseToTitlebar;	// IMP=0x0042ca62
- (long long)_shadowType;	// IMP=0x000610df
- (unsigned long long)_shadowFlags;	// IMP=0x000ce117
- (struct CGSize)_shadowOffset;	// IMP=0x000cdf12
- (void)_setShadowParameters;	// IMP=0x000cdcf7
- (void)_drawFrameShadowAndFlushContext:(id)arg1;	// IMP=0x00060fdf
- (void)setUpGState;	// IMP=0x00051282
- (void)adjustHalftonePhase;	// IMP=0x00051293
- (void)systemColorsDidChange:(id)arg1;	// IMP=0x0042d178
- (id)frameColor;	// IMP=0x0042d058
- (id)contentFill;	// IMP=0x0042cf76
- (void)tabViewAdded;	// IMP=0x0042ca6c
- (void)tabViewRemoved;	// IMP=0x0042ca7c
- (id)title;	// IMP=0x00066898
- (void)setTitle:(id)arg1;	// IMP=0x00206116
- (id)titleCell;	// IMP=0x00085878
- (void)initTitleCell:(id)arg1;	// IMP=0x002066fe
- (void)setResizeIncrements:(struct CGSize)arg1;	// IMP=0x0042cf25
- (struct CGSize)resizeIncrements;	// IMP=0x0015c500
- (void)setAspectRatio:(struct CGSize)arg1;	// IMP=0x0042ca95
- (struct CGSize)aspectRatio;	// IMP=0x0015a70f
- (unsigned long long)styleMask;	// IMP=0x000423ca
- (id)representedFilename;	// IMP=0x0042cf03
- (void)setRepresentedFilename:(id)arg1;	// IMP=0x0042cab8
- (void)setDocumentEdited:(BOOL)arg1;	// IMP=0x0042cabe
- (void)_setFrameNeedsDisplay:(BOOL)arg1;	// IMP=0x002446b9
- (BOOL)frameNeedsDisplay;	// IMP=0x0042cac4
- (id)defaultTitleFont;	// IMP=0x00206800
- (id)titleFont;	// IMP=0x0042ceef
- (struct CGRect)_maxTitlebarTitleRect;	// IMP=0x0042cacc
- (struct CGRect)titlebarRect;	// IMP=0x0042cecd
- (void)_setUtilityWindow:(BOOL)arg1;	// IMP=0x0042ce89
- (void)_setNonactivatingPanel:(BOOL)arg1;	// IMP=0x0042ce40
- (void)setIsClosable:(BOOL)arg1;	// IMP=0x0042cdfc
- (void)setIsResizable:(BOOL)arg1;	// IMP=0x0042cdb8
- (void)setStyleMask:(unsigned long long)arg1;	// IMP=0x001996eb
- (id)closeButton;	// IMP=0x0010beba
- (id)minimizeButton;	// IMP=0x0010becb
- (id)zoomButton;	// IMP=0x0012a53b
- (struct CGSize)miniaturizedSize;	// IMP=0x0042cd8d
- (void)_clearDragMargins;	// IMP=0x0012a328
- (struct CGRect)_draggableFrame;	// IMP=0x0042ccf7
- (void)_resetDragMargins;	// IMP=0x00129ae0
- (void)addSubview:(id)arg1;	// IMP=0x00199a8d
- (void)setTitle:(id)arg1 andDefeatWrap:(BOOL)arg2;	// IMP=0x0042cce6
- (struct CGRect)frameRectForContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x000729cd
- (struct CGRect)contentRectForFrameRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x000e6cdd
- (struct CGSize)minFrameSizeForMinContentSize:(struct CGSize)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x0042cca0
- (struct CGRect)dragRectForFrameRect:(struct CGRect)arg1;	// IMP=0x0042cb81
- (struct CGRect)contentRect;	// IMP=0x0042cc7e
- (struct CGSize)minFrameSize;	// IMP=0x0042cbb7
- (void)updateTrackingAreas;	// IMP=0x0016cd81
- (id)_edgeResizingTrackingAreas;	// IMP=0x0016d6e1

@end

