/*
 *     Generated by class-dump 3.3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSTitledFrame.h"

@class NSButton, NSString;

@interface NSThemeFrame : NSTitledFrame
{
    NSButton *toolbarButton;
    int toolbarVisibleStatus;
    struct CGLayer *showToolbarTransitionLayer;
    struct CGSize showToolbarPreWindowSize;
    NSButton *fullScreenButton;
    long long leftGroupTrackingTagNum;
    long long rightGroupTrackingTagNum;
    struct {
        unsigned int mouseInsideLeftGroup:1;
        unsigned int mouseInsideRightGroup:1;
        unsigned int bottomCornerRounded:2;
        unsigned int movableByBottomBar:1;
        unsigned int removingToolbarForEnteringFullScreen:1;
        unsigned int suppressTitleBackgroundDrawing:1;
        unsigned int suppressTitleDrawing:1;
        unsigned int reserved:24;
    } _tFlags;
    int widgetState;
    NSString *displayName;
    NSButton *lockButton;
    double topBorderThickness;
    double bottomBorderThickness;
}

+ (void)initialize;	// IMP=0x00203508
+ (Class)_shadowViewClass;	// IMP=0x00639c2e
+ (id)_bevelForEdge:(unsigned long long)arg1 isHUD:(BOOL)arg2 isDarkWindow:(BOOL)arg3;	// IMP=0x00160c8a
+ (void)drawBevel:(struct CGRect)arg1 inFrame:(struct CGRect)arg2 topCornerRounded:(BOOL)arg3 bottomCornerRounded:(BOOL)arg4 isHUD:(BOOL)arg5 isDarkWindow:(BOOL)arg6;	// IMP=0x0063a627
+ (void)drawBevel:(struct CGRect)arg1 inFrame:(struct CGRect)arg2 topCornerRounded:(BOOL)arg3 bottomCornerRounded:(BOOL)arg4;	// IMP=0x0063a5c0
+ (double)_windowBorderThickness:(unsigned long long)arg1;	// IMP=0x00639e2b
+ (double)_minXWindowBorderWidth:(unsigned long long)arg1;	// IMP=0x00072b6d
+ (double)_maxXWindowBorderWidth:(unsigned long long)arg1;	// IMP=0x00072bab
+ (double)_minYWindowBorderHeight:(unsigned long long)arg1;	// IMP=0x00639e35
+ (double)_windowTitlebarButtonSpacingWidth:(unsigned long long)arg1;	// IMP=0x0063a530
+ (double)_windowFileButtonSpacingWidth:(unsigned long long)arg1;	// IMP=0x00639e3f
+ (double)_minXTitlebarWidgetInset:(unsigned long long)arg1;	// IMP=0x0063a498
+ (double)_maxXTitlebarWidgetInset:(unsigned long long)arg1;	// IMP=0x00639e4d
+ (double)minFrameWidthWithTitle:(id)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x0063a36d
+ (double)_windowSideTitlebarTitleMinWidth:(unsigned long long)arg1;	// IMP=0x0063a2cc
+ (double)_windowTitlebarTitleMinHeight:(unsigned long long)arg1;	// IMP=0x00072beb
+ (double)_sideTitlebarWidth:(unsigned long long)arg1;	// IMP=0x0063a2ba
+ (double)_titlebarHeight:(unsigned long long)arg1;	// IMP=0x00072bd9
+ (double)_resizeHeight:(unsigned long long)arg1;	// IMP=0x00072b8c
+ (BOOL)_resizeFromEdge;	// IMP=0x00639e6a
+ (struct CGSize)sizeOfTitlebarButtons:(unsigned long long)arg1;	// IMP=0x00086771
+ (double)_contentToFrameMinXWidth:(unsigned long long)arg1;	// IMP=0x00072b4a
+ (double)_contentToFrameMaxXWidth:(unsigned long long)arg1;	// IMP=0x00072b99
+ (double)_contentToFrameMinYHeight:(unsigned long long)arg1;	// IMP=0x00072b78
+ (double)_contentToFrameMaxYHeight:(unsigned long long)arg1;	// IMP=0x00072bb5
+ (unsigned long long)_validateStyleMask:(unsigned long long)arg1;	// IMP=0x00254972
- (BOOL)_isDarkWindow;	// IMP=0x0005218c
- (BOOL)_movableByBottomBar;	// IMP=0x00239f29
- (void)_setMovableByBottomBar:(BOOL)arg1;	// IMP=0x00639c0b
- (BOOL)_effectiveMovableByBottomBar;	// IMP=0x0012918d
- (float)roundedCornerRadius;	// IMP=0x00060447
- (void)setBottomCornerRounded:(BOOL)arg1;	// IMP=0x0019b536
- (BOOL)bottomCornerRounded;	// IMP=0x00051df3
- (struct CGSize)_topCornerSize;	// IMP=0x0015ee2b
- (struct CGSize)_bottomCornerSize;	// IMP=0x000603dc
- (struct CGRect)_bottomCornerRect;	// IMP=0x00147896
- (struct CGSRegionObject *)_createWindowOpaqueShape;	// IMP=0x0023925f
- (void)shapeWindow;	// IMP=0x0015eb6f
- (struct CGRect)_shadowRect;	// IMP=0x0063eac0
- (void)_addShadowViewAboveContentView:(id)arg1;	// IMP=0x0063e9c3
- (void)_maskCorners:(struct CGRect)arg1;	// IMP=0x000ccfe1
- (void)_setContentView:(id)arg1;	// IMP=0x002055d8
- (void)_recursiveDisplayRectIfNeededIgnoringOpacity:(struct CGRect)arg1 isVisibleRect:(BOOL)arg2 rectIsVisibleRectForView:(id)arg3 topView:(BOOL)arg4;	// IMP=0x000519a5
- (struct CGRect)overlayBounds;	// IMP=0x0005fd4e
- (void)drawOverlayRect:(struct CGRect)arg1;	// IMP=0x000ccd3c
- (struct CGSRegionObject *)_regionForOpaqueDescendants:(struct CGRect)arg1 forMove:(BOOL)arg2;	// IMP=0x00055494
- (void)_drawFrameInterior:(struct CGRect *)arg1 clip:(struct CGRect)arg2;	// IMP=0x00084e8b
- (void)_setTextShadow:(BOOL)arg1;	// IMP=0x0063e946
- (BOOL)_isOnePieceTitleAndToolbar;	// IMP=0x0023b348
- (struct CGRect)_separatorRectForInactiveWindow;	// IMP=0x0063e8ad
- (void)_setFrameNeedsDisplay:(BOOL)arg1;	// IMP=0x002444ff
- (void)_drawUnifiedToolbarBackgroundInRect:(struct CGRect)arg1 withState:(long long)arg2;	// IMP=0x0063e6bb
- (void)_drawUnifiedToolbar:(int)arg1;	// IMP=0x0023b362
- (void)_drawTitleBar:(struct CGRect)arg1;	// IMP=0x0023ad2b
- (void)_drawResizeIndicators:(struct CGRect)arg1;	// IMP=0x0063e5f0
- (void)_drawFrameRects:(struct CGRect)arg1;	// IMP=0x0063e530
- (void)drawFrame:(struct CGRect)arg1;	// IMP=0x00084b46
- (BOOL)_isHUDWindow;	// IMP=0x00052170
- (id)contentFill;	// IMP=0x0023a197
- (void)viewDidEndLiveResize;	// IMP=0x0016c747
- (double)contentAlpha;	// IMP=0x00084378
- (void)setThemeFrameWidgetState:(int)arg1;	// IMP=0x0063e515
- (void)addFileButton:(id)arg1;	// IMP=0x0063e4d9
- (void)_setButtonsShown:(BOOL)arg1;	// IMP=0x0019972a
- (void)_updateButtons;	// IMP=0x00199da9
- (void)_updateButtonState;	// IMP=0x001a6b1e
- (id)newCloseButton;	// IMP=0x00204043
- (id)newZoomButton;	// IMP=0x0020523e
- (id)newMiniaturizeButton;	// IMP=0x00205361
- (id)newToolbarButton;	// IMP=0x0063e45c
- (id)newLockButton;	// IMP=0x0063e3df
- (id)newFileButton;	// IMP=0x002759df
- (id)newAutosaveButton;	// IMP=0x0027476a
- (id)newFullScreenButton;	// IMP=0x002826a1
- (id)makeRenameField;	// IMP=0x0063e30d
- (void)_resetTitleBarButtons;	// IMP=0x0063e1f0
- (void)setDocumentEdited:(BOOL)arg1;	// IMP=0x0063e14e
- (void)_setDocumentEditingState:(long long)arg1 animate:(BOOL)arg2;	// IMP=0x00299794
- (long long)_documentEditingState;	// IMP=0x0063e11e
- (void)_setDocumentButtonEnabled:(BOOL)arg1;	// IMP=0x0063e0ff
- (void)_setDocumentAutosavingError:(id)arg1;	// IMP=0x0063e07e
- (id)_documentAutosavingError;	// IMP=0x0063e050
- (id)toolbarButton;	// IMP=0x0010bede
- (id)lockButton;	// IMP=0x00639e07
- (id)autosaveButton;	// IMP=0x00086a3b
- (void)_setAutosaveButton:(id)arg1;	// IMP=0x00275871
- (id)_autosaveButtonSeparatorField;	// IMP=0x0063e03c
- (void)_setAutosaveButtonSeparatorField:(id)arg1;	// IMP=0x0063e026
- (id)_shadowView;	// IMP=0x0063e015
- (void)_setShadowView:(id)arg1;	// IMP=0x0063dfff
- (id)renameField;	// IMP=0x00085cf2
- (void)_setRenameField:(id)arg1;	// IMP=0x0063dfe8
- (id)fullScreenButton;	// IMP=0x0010bef0
- (id)_buttonHidingView;	// IMP=0x0019a8ab
- (void)_setButtonHidingView:(id)arg1;	// IMP=0x00199afd
- (id)initWithFrame:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 owner:(id)arg3;	// IMP=0x00203ccb
- (void)setStyleMask:(unsigned long long)arg1;	// IMP=0x00199347
- (void)viewWillMoveToWindow:(id)arg1;	// IMP=0x00203fa4
- (void)dealloc;	// IMP=0x0024344f
- (BOOL)preservesContentDuringLiveResize;	// IMP=0x00160c6e
- (void)setBoundsSize:(struct CGSize)arg1;	// IMP=0x0063df94
- (void)_positionShadowView;	// IMP=0x0063df23
- (void)_hideShadowView;	// IMP=0x0063def0
- (void)_showShadowView;	// IMP=0x0063debd
- (void)setFrameSize:(struct CGSize)arg1;	// IMP=0x0015dbfd
- (BOOL)_canHaveToolbar;	// IMP=0x0028e285
- (BOOL)_toolbarIsInTransition;	// IMP=0x0007209c
- (BOOL)_toolbarIsShown;	// IMP=0x00066f65
- (BOOL)_toolbarIsHidden;	// IMP=0x0019bf88
- (BOOL)_toolbarIsManagedByExternalWindow;	// IMP=0x0019c09b
- (id)_toolbarView;	// IMP=0x000720be
- (id)_toolbar;	// IMP=0x0019c438
- (double)_distanceFromToolbarBaseToTitlebar;	// IMP=0x00071c37
- (unsigned long long)_shadowFlags;	// IMP=0x000cdfc9
- (struct CGRect)frameRectForContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x00072921
- (struct CGRect)contentRectForFrameRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x000e6c2d
- (struct CGSize)minFrameSizeForMinContentSize:(struct CGSize)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x0063de64
- (struct CGRect)contentRect;	// IMP=0x0019e463
- (struct CGRect)_contentRectExcludingToolbar;	// IMP=0x00283832
- (struct CGRect)_contentRectIncludingToolbarAtHome;	// IMP=0x0028379f
- (void)_setToolbarShowHideResizeWeightingOptimizationOn:(BOOL)arg1;	// IMP=0x0019d177
- (BOOL)_usingToolbarShowHideWeightingOptimization;	// IMP=0x00158148
- (void)handleSetFrameCommonRedisplay;	// IMP=0x00164ca5
- (void)_startLiveResizeAsTopLevel;	// IMP=0x001580de
- (void)_endLiveResizeAsTopLevel;	// IMP=0x0016b0ab
- (void)_growContentReshapeContentAndToolbarView:(int)arg1 animate:(BOOL)arg2;	// IMP=0x00283249
- (BOOL)_growWindowReshapeContentAndToolbarView:(int)arg1 animate:(BOOL)arg2;	// IMP=0x0019c471
- (void)_reshapeContentAndToolbarView:(int)arg1 resizeWindow:(BOOL)arg2 animate:(BOOL)arg3;	// IMP=0x0019c2e8
- (void)_toolbarFrameSizeChanged:(id)arg1 oldSize:(struct CGSize)arg2;	// IMP=0x0063dd01
- (void)_syncToolbarPosition;	// IMP=0x0063dbbd
- (void)_syncInspectorBarPosition;	// IMP=0x00160749
- (void)_showHideToolbar:(int)arg1 resizeWindow:(BOOL)arg2 animate:(BOOL)arg3;	// IMP=0x0019c0b3
- (void)_showToolbarWithAnimation:(BOOL)arg1;	// IMP=0x0028318c
- (void)_hideToolbarWithAnimation:(BOOL)arg1;	// IMP=0x0019c004
- (void)_surrenderToolbarViewForFullScreenWindow;	// IMP=0x0019bfaf
- (void)_reacquireToolbarViewFromFullScreenWindowAndShow:(BOOL)arg1;	// IMP=0x00283164
- (void)_drawToolbarTransitionIfNecessary;	// IMP=0x000894cf
- (void)_computeHeightOfTop:(BOOL)arg1 bottom:(BOOL)arg2;	// IMP=0x002055af
- (void)setContentBorderThickness:(double)arg1 forEdge:(unsigned long long)arg2;	// IMP=0x00238a34
- (double)contentBorderThicknessForEdge:(unsigned long long)arg1;	// IMP=0x0008456e
- (double)_topBarHeight;	// IMP=0x00084513
- (double)_bottomBarHeight;	// IMP=0x000886d5
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x0023a3b2
- (void)drawWindowBackgroundRect:(struct CGRect)arg1;	// IMP=0x0023b8e6
- (void)drawWindowBackgroundRegion:(struct CGSRegionObject *)arg1;	// IMP=0x0027d0f2
- (BOOL)shouldBeTreatedAsInkEvent:(id)arg1;	// IMP=0x00639e1b
- (BOOL)_shouldBeTreatedAsInkEventInInactiveWindow:(id)arg1;	// IMP=0x00639e23
- (id)_hitTest:(struct CGPoint)arg1 ignoringResizeRegion:(BOOL)arg2;	// IMP=0x00070339
- (id)hitTest:(struct CGPoint)arg1;	// IMP=0x00070323
- (void)cursorUpdate:(id)arg1;	// IMP=0x0012adfe
- (struct CGRect)_leftGroupRect;	// IMP=0x001086ef
- (struct CGRect)_rightGroupRect;	// IMP=0x00108a71
- (void)_updateWidgets;	// IMP=0x001085c1
- (void)_updateMouseTracking;	// IMP=0x0016041f
- (void)mouseEntered:(id)arg1;	// IMP=0x0063dad9
- (void)mouseExited:(id)arg1;	// IMP=0x0063d9fa
- (void)_setMouseEnteredGroup:(BOOL)arg1 entered:(BOOL)arg2;	// IMP=0x00108ba6
- (BOOL)_mouseInGroup:(id)arg1;	// IMP=0x0008a2f4
- (id)_hitTestToBlockWindowResizing:(struct CGPoint)arg1 forResizeDirection:(long long)arg2;	// IMP=0x00156803
- (struct CGSize)miniaturizedSize;	// IMP=0x0063d9b3
- (double)_minXTitlebarDecorationMinWidth;	// IMP=0x0008650d
- (double)_maxXTitlebarDecorationMinWidth;	// IMP=0x000868ec
- (struct CGSize)minFrameSize;	// IMP=0x0015b8b6
- (double)_windowBorderThickness;	// IMP=0x00639e74
- (double)_windowTitlebarXResizeBorderThickness;	// IMP=0x00639e7e
- (double)_windowTitlebarYResizeBorderThickness;	// IMP=0x00639e88
- (double)_windowResizeBorderThickness;	// IMP=0x00639e92
- (double)_minXWindowBorderWidth;	// IMP=0x000864f8
- (double)_maxXWindowBorderWidth;	// IMP=0x00086502
- (double)_minYWindowBorderHeight;	// IMP=0x0015b9e0
- (double)_maxYWindowBorderHeight;	// IMP=0x00639e9e
- (void)_size:(struct CGSize *)arg1 ofCell:(id)arg2 withTitle:(id)arg3;	// IMP=0x00085d04
- (struct CGSize)_titleCellSize;	// IMP=0x0008579f
- (double)_minYTitlebarButtonsOffset;	// IMP=0x0015ff55
- (double)_minYTitlebarTitleOffset;	// IMP=0x00639ea8
- (double)_sideTitlebarWidth;	// IMP=0x0063d974
- (double)_titlebarHeight;	// IMP=0x0008459b
- (struct CGRect)_defaultTitlebarTitleRect;	// IMP=0x0008546b
- (struct CGRect)_titlebarTitleRect;	// IMP=0x00085342
- (struct CGRect)titlebarRect;	// IMP=0x0008633e
- (double)_windowTitlebarTitleMinHeight;	// IMP=0x0063d935
- (struct CGSize)_sizeOfTitlebarFileButton;	// IMP=0x00275d73
- (struct CGSize)sizeOfTitlebarToolbarButton;	// IMP=0x0063d901
- (double)_windowTitlebarButtonSpacingWidth;	// IMP=0x00086822
- (double)_windowFileButtonSpacingWidth;	// IMP=0x00275d9e
- (double)_minXTitlebarWidgetInset;	// IMP=0x002053de
- (double)_maxXTitlebarWidgetInset;	// IMP=0x0063d8d8
- (double)_minXTitlebarButtonsWidth;	// IMP=0x00086586
- (double)_maxXTitlebarButtonsWidth;	// IMP=0x00086994
- (struct CGPoint)_closeButtonOrigin;	// IMP=0x0015fd8c
- (struct CGPoint)_zoomButtonOrigin;	// IMP=0x001600d4
- (struct CGPoint)_fullScreenButtonOrigin;	// IMP=0x001601b5
- (struct CGPoint)_collapseButtonOrigin;	// IMP=0x0015fff1
- (struct CGPoint)_toolbarButtonOrigin;	// IMP=0x0063d793
- (struct CGPoint)_lockButtonOrigin;	// IMP=0x0063d63c
- (struct CGPoint)_fileButtonOrigin;	// IMP=0x00275c18
- (struct CGPoint)_autosaveButtonSeparatorFieldOrigin;	// IMP=0x0063d574
- (struct CGPoint)_autosaveButtonOrigin;	// IMP=0x0027588a
- (void)_tileTitlebarAndRedisplay:(BOOL)arg1;	// IMP=0x0015fa0e
- (struct CGRect)_commandPopupRect;	// IMP=0x00280828
- (struct CGRect)_clickableAutosaveButtonRect;	// IMP=0x0063d4a4
- (struct CGRect)_draggableFrame;	// IMP=0x00129ea0
- (void)_resetDragMargins;	// IMP=0x0012939f
- (double)_maxYTitlebarDragHeight;	// IMP=0x0063d492
- (double)_minXTitlebarDragWidth;	// IMP=0x0063d481
- (double)_maxXTitlebarDragWidth;	// IMP=0x0063d470
- (double)_contentToFrameMinXWidth;	// IMP=0x0019e60c
- (double)_contentToFrameMaxXWidth;	// IMP=0x0019e64f
- (double)_contentToFrameMinYHeight;	// IMP=0x0015b9ce
- (double)_contentToFrameMaxYHeight;	// IMP=0x0015b9ed
- (struct CGRect)_maxXminYResizeRect;	// IMP=0x00051fad
- (struct CGRect)_minXBorderRect;	// IMP=0x0063d39b
- (struct CGRect)_maxXBorderRect;	// IMP=0x00639eb8
- (struct CGRect)_maxYBorderRect;	// IMP=0x0063d2bf
- (struct CGRect)_minYBorderRect;	// IMP=0x0063d1e9
- (void)_invalidateTitleCellSize;	// IMP=0x00204016
- (void)_resetTitleFont;	// IMP=0x0063d185
- (BOOL)_isUtility;	// IMP=0x000602b7
- (double)_sheetHeightAdjustment;	// IMP=0x0063d111
- (void)_setSheet:(BOOL)arg1;	// IMP=0x0063cee4
- (BOOL)_isSheet;	// IMP=0x0006146e
- (BOOL)_isResizable;	// IMP=0x00070556
- (BOOL)_isClosable;	// IMP=0x0019a791
- (BOOL)_isMiniaturizable;	// IMP=0x0019b29e
- (BOOL)_isFullScreen;	// IMP=0x00084634
- (BOOL)_hidingTitlebar;	// IMP=0x000845ff
- (BOOL)_hidingToolbar;	// IMP=0x00071edc
- (BOOL)_hasToolbar;	// IMP=0x00071eb9
- (struct CGRect)_growBoxRect;	// IMP=0x0063ccec
- (BOOL)_canDrawWindowGrowBox;	// IMP=0x00639ef1
- (void)_drawGrowBoxWithClip:(struct CGRect)arg1 inRect:(struct CGRect)arg2 opaque:(BOOL)arg3;	// IMP=0x0063ca99
- (void)_drawGrowBoxWithClip:(struct CGRect)arg1;	// IMP=0x0063c9f8
- (BOOL)_inactiveButtonsNeedMask;	// IMP=0x00639efc
- (BOOL)_mouseInPopupRect:(id)arg1;	// IMP=0x0063c965
- (BOOL)_mouseInTitleRect:(id)arg1;	// IMP=0x0024dbc6
- (void)_document:(id)arg1 didRename:(BOOL)arg2 contextInfo:(void *)arg3;	// IMP=0x0063c91b
- (void)_makeRenameFieldResignFirstResponder:(id)arg1;	// IMP=0x0063c8de
- (void)controlTextDidChange:(id)arg1;	// IMP=0x0063c87e
- (void)controlTextDidEndEditing:(id)arg1;	// IMP=0x0063c58f
- (BOOL)isPartialStringValid:(id *)arg1 proposedSelectedRange:(struct _NSRange *)arg2 originalString:(id)arg3 originalSelectedRange:(struct _NSRange)arg4 errorDescription:(id *)arg5;	// IMP=0x0063c507
- (void)editTitle:(id)arg1;	// IMP=0x0063bf5d
- (BOOL)acceptsFirstMouse:(id)arg1;	// IMP=0x0024db95
- (void)mouseUp:(id)arg1;	// IMP=0x0016cb5d
- (void)mouseDown:(id)arg1;	// IMP=0x00157307
- (void)rightMouseDown:(id)arg1;	// IMP=0x0063bed5
- (id)menu;	// IMP=0x0063be12
- (id)menuForEvent:(id)arg1;	// IMP=0x0063bcc7
- (id)_displayName;	// IMP=0x00639f07
- (void)_setDisplayName:(id)arg1;	// IMP=0x002761e4
- (BOOL)_shouldRepresentFilename;	// IMP=0x0063bc57
- (BOOL)_shouldShowDocumentIcon;	// IMP=0x000868c0
- (void)setRepresentedURL:(id)arg1;	// IMP=0x0022f277
- (void)setRepresentedFilename:(id)arg1;	// IMP=0x0063bbcc
- (void)_invalidateDocumentIcon;	// IMP=0x0063bbad
- (void)setTitle:(id)arg1;	// IMP=0x0063bafa
- (id)_snapshotCurrentTitleControlStateInRect:(struct CGRect)arg1;	// IMP=0x0063ba5e
- (struct CGRect)_titleControlRect;	// IMP=0x0063b8a0
- (void)_snapshotStartingTitleControlState;	// IMP=0x0063b72d
- (void)_setSuppressTitleControlDrawing:(BOOL)arg1;	// IMP=0x0063b687
- (void)_animateFromStartingTitleControlState;	// IMP=0x0063b58b
- (void)animationDidEnd:(id)arg1;	// IMP=0x0063b52b
- (void)animationDidStop:(id)arg1;	// IMP=0x0063b4cb

@end

