/*
 *     Generated by class-dump 3.3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>
#import "NSFrameView.h"

@interface NSTitledFrame : NSFrameView
{
    long long resizeFlags;
    struct CGSize titleCellSize;
}

+ (void)initialize;	// IMP=0x00203446
+ (double)_windowBorderThickness:(unsigned long long)arg1;	// IMP=0x00642440
+ (double)_minXWindowBorderWidth:(unsigned long long)arg1;	// IMP=0x006429c2
+ (double)_maxXWindowBorderWidth:(unsigned long long)arg1;	// IMP=0x006429a8
+ (double)_minYWindowBorderHeight:(unsigned long long)arg1;	// IMP=0x0064298e
+ (BOOL)_resizeFromEdge;	// IMP=0x0064245b
+ (struct CGRect)frameRectForContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x00072a35
+ (struct CGRect)contentRectForFrameRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x000e6d45
+ (struct CGSize)minFrameSizeForMinContentSize:(struct CGSize)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x0007308e
+ (struct CGSize)minContentSizeForMinFrameSize:(struct CGSize)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x006428f2
+ (double)minFrameWidthWithTitle:(id)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x006427be
+ (struct CGSize)_titleCellSizeForTitle:(id)arg1 styleMask:(unsigned long long)arg2;	// IMP=0x0064263b
+ (double)_titleCellHeight:(unsigned long long)arg1;	// IMP=0x0064261b
+ (double)_windowTitlebarTitleMinHeight:(unsigned long long)arg1;	// IMP=0x006425fd
+ (double)_titlebarHeight:(unsigned long long)arg1;	// IMP=0x00642575
+ (struct CGSize)sizeOfTitlebarButtons:(unsigned long long)arg1;	// IMP=0x00642463
+ (double)windowTitlebarLinesSpacingWidth:(unsigned long long)arg1;	// IMP=0x00642482
+ (double)windowTitlebarTitleLinesSpacingWidth:(unsigned long long)arg1;	// IMP=0x0064249d
+ (double)_contentToFrameMinXWidth:(unsigned long long)arg1;	// IMP=0x0064255b
+ (double)_contentToFrameMaxXWidth:(unsigned long long)arg1;	// IMP=0x00642541
+ (double)_contentToFrameMinYHeight:(unsigned long long)arg1;	// IMP=0x00642527
+ (double)_contentToFrameMaxYHeight:(unsigned long long)arg1;	// IMP=0x00642505
- (void)dealloc;	// IMP=0x00243499
- (BOOL)isOpaque;	// IMP=0x0004608b
- (BOOL)worksWhenModal;	// IMP=0x00644f93
- (void)propagateFrameDirtyRects:(struct CGRect)arg1;	// IMP=0x0064497a
- (void)_showDrawRect:(struct CGRect)arg1;	// IMP=0x006445a9
- (id)frameHighlightColor;	// IMP=0x00644489
- (id)frameShadowColor;	// IMP=0x00644369
- (void)setFrameOrigin:(struct CGPoint)arg1;	// IMP=0x00642429
- (void)tileAndSetWindowShape:(BOOL)arg1;	// IMP=0x00205512
- (void)tile;	// IMP=0x00644353
- (void)setTitle:(id)arg1;	// IMP=0x00205a5f
//- (void)_drawTitleStringIn:(struct CGRect)arg1 withColor:(id)arg2;	// IMP=0x00085115
- (void)_drawTitleStringIn:(NSRect)fp8 withColor:(id)fp24;
- (id)titleFont;	// IMP=0x002067cb
- (id)titleButtonOfClass:(Class)arg1;	// IMP=0x00644296
- (id)initTitleButton:(id)arg1;	// IMP=0x006441c6
- (id)newCloseButton;	// IMP=0x006440b7
- (id)newZoomButton;	// IMP=0x00643fa8
- (id)newMiniaturizeButton;	// IMP=0x00643e99
- (id)newFileButton;	// IMP=0x00643d9f
- (id)fileButton;	// IMP=0x00280814
- (BOOL)_eventInTitlebar:(id)arg1;	// IMP=0x00643cba
- (BOOL)acceptsFirstMouse:(id)arg1;	// IMP=0x00299ba1
- (void)mouseDown:(id)arg1;	// IMP=0x001575d4
- (void)_minimizeWindowWithDoubleClick:(id)arg1;	// IMP=0x00643c1a
- (void)_zoomWindowWithDoubleClick:(id)arg1;	// IMP=0x00643bc7
- (void)mouseUp:(id)arg1;	// IMP=0x0016cbed
- (struct CGRect)_validFrameForResizeFrame:(struct CGRect)arg1 fromResizeEdge:(unsigned long long)arg2;	// IMP=0x0015b6d0
- (struct CGSRegionObject *)_regionForOpaqueDescendants:(struct CGRect)arg1 forMove:(BOOL)arg2;	// IMP=0x00055844
- (void)resizeWithEvent:(id)arg1;	// IMP=0x001576cf
- (long long)resizeFlags;	// IMP=0x0064242f
- (void)setDocumentEdited:(BOOL)arg1;	// IMP=0x006439d8
- (struct CGSize)miniaturizedSize;	// IMP=0x00643974
- (struct CGSize)minFrameSize;	// IMP=0x006438e9
- (double)_windowBorderThickness;	// IMP=0x006438c1
- (double)_windowTitlebarXResizeBorderThickness;	// IMP=0x006438a7
- (double)_windowTitlebarYResizeBorderThickness;	// IMP=0x00643885
- (double)_windowResizeBorderThickness;	// IMP=0x0064385b
- (double)_minXWindowBorderWidth;	// IMP=0x00643841
- (double)_maxXWindowBorderWidth;	// IMP=0x00643827
- (double)_minYWindowBorderHeight;	// IMP=0x0064380d
- (id)_customTitleCell;	// IMP=0x000852da
- (void)_invalidateTitleCellWidth;	// IMP=0x002061e8
- (double)_titleCellHeight;	// IMP=0x0064375e
- (struct CGSize)_titleCellSize;	// IMP=0x00643559
- (double)_titlebarHeight;	// IMP=0x006434d9
- (struct CGRect)titlebarRect;	// IMP=0x006433fa
- (struct CGRect)_maxTitlebarTitleRect;	// IMP=0x00086267
- (struct CGRect)_titlebarTitleRect;	// IMP=0x006424ab
- (double)_windowTitlebarTitleMinHeight;	// IMP=0x006433dc
- (struct CGRect)dragRectForFrameRect:(struct CGRect)arg1;	// IMP=0x00106d0d
- (struct CGSize)sizeOfTitlebarButtons;	// IMP=0x0008672a
- (struct CGSize)_sizeOfTitlebarFileButton;	// IMP=0x006424e1
- (double)_windowTitlebarButtonSpacingWidth;	// IMP=0x006433b4
- (double)_minXTitlebarButtonsWidth;	// IMP=0x00643377
- (double)_maxXTitlebarButtonsWidth;	// IMP=0x00643323
- (double)windowTitlebarLinesSpacingWidth;	// IMP=0x006432fb
- (double)windowTitlebarTitleLinesSpacingWidth;	// IMP=0x006424f7
- (double)_minLinesWidthWithSpace;	// IMP=0x006432b8
- (struct CGPoint)_closeButtonOrigin;	// IMP=0x006431fd
- (struct CGPoint)_zoomButtonOrigin;	// IMP=0x00643120
- (struct CGPoint)_collapseButtonOrigin;	// IMP=0x00643066
- (struct CGPoint)_fileButtonOrigin;	// IMP=0x00642f8a
- (double)_maxYTitlebarDragHeight;	// IMP=0x00642f68
- (double)_minXTitlebarDragWidth;	// IMP=0x00642f4e
- (double)_maxXTitlebarDragWidth;	// IMP=0x00642f34
- (double)_contentToFrameMinXWidth;	// IMP=0x00642f1a
- (double)_contentToFrameMaxXWidth;	// IMP=0x00642f00
- (double)_contentToFrameMinYHeight;	// IMP=0x00642ee6
- (double)_contentToFrameMaxYHeight;	// IMP=0x00642ec4
- (struct CGRect)contentRect;	// IMP=0x0019e4f0
- (double)_windowResizeCornerThickness;	// IMP=0x00642e9c
- (struct CGRect)_maxXminYResizeRect;	// IMP=0x00642d45
- (struct CGRect)_minXBorderRect;	// IMP=0x00642c96
- (struct CGRect)_maxXBorderRect;	// IMP=0x00642be4
- (struct CGRect)_maxYBorderRect;	// IMP=0x00642ae0
- (struct CGRect)_minYBorderRect;	// IMP=0x006429dc

@end

